### ISSUE TITLE
Make ManagementPortal user properties configurable

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-base/ManagementPortal#709]
Specifically the following fields should be made optional as specified in frontend setup:
- Name
- Birth date
- Group

This is just a frontend customisation, those fields are optional in the backend already. Specifically, the following pages should be modified:
- Participant edit / info screen
- Per-property filtering turned off or on
- Group tab hidden / shown

The frontend should get informed of what features to enable via a REST request. Ideally, this request goes to ManagementPortal backend, otherwise the Dockerfile needs to add an entrypoint script to fill in the configured values when the container is started up.
```[tasklist]
### Tasks
- [x] add all to group checkboxes should be hidden
- [x] remove hidden fields in pairing dialogue
- [x] handle info-screen
- [x] handle participant-edit
- [x] handle per-property filtering
- [x] handle group tab
- [x] implement requirements on the backend
```
