### ISSUE TITLE
Update Node.js in docker-compose.yml to 18+

### ISSUE THREAD

**Issue by Bdegraaf1234** [RADAR-base/ManagementPortal#721]
the newest Node.js update broke our build and required us to either add --openssl-legacy-provider flag to our build or continue using node v<17 (see  commit e9bc5e53054f8dcf1676d788c1b0642aa02256af)

This is a security risk as outlined [here](https://stackoverflow.com/a/73027407). To fix this we need to upgrade to node.js >17 in all our build scripts.

This requires updating angular as well.

Ideally we make a new release before doing this.

```[tasklist]
### Tasks
- [ ] Create release 2.1.0
- [ ] Update NodeJs
- [ ] Update dependencies (including Angular)
- [ ] Run yarn security audit (equivalent of ```npm audit fix --force```)
- [ ] Remove the NODE_OPTIONS=--openssl-legacy-provider flag from all  builds 
```
